run: # Configurations for a specific run
  random_seed: 1236 # Integer number of specifying random seed
  log_dir: ./target # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.

train:
  epochs: 20
  batch_size: 256
  optimizer: SGD
  learning_rate: 0.1
  momentum: 0.9        # (if using SGD)
  weight_decay: 0.0005
  nesterov: True

data: # Configuration for data
  dataset: cifar10 # String indicates the name of the dataset
  f_train: 0.5 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.5 # Float number from 0 to 1 indicating the size of the test set
  data_dir: ./data # String about where to save the data.